### ISSUE TITLE
overflow inside cards

### ISSUE THREAD

**Issue by SeeThruHead** [glenjamin/devcards-js#29] opened 2016-02-12 19:20 UTC
Hey! I've been using this project for a little bit (thanks so much!) from github.

I did a fresh npm install today and noticed this

https://www.dropbox.com/s/tse9y9qk5c4y01j/Screenshot%202016-02-12%2014.17.39.png?dl=0

I tried to find what commit caused it but I didn't quite find it.

anyway i just thought I'd bring it to your attention, I'm going to take another stab at finding out the cause sometime over the weekend.

**Comment by glenjamin** [comment] 2016-02-13 11:44
I'm not clear what the problem is in that screenshot - could you be more specific?

**Comment by glenjamin** [comment] 2016-02-22 20:59
Oh, is the problem that elements which try and overflow get clipped at the card border?

**Comment by SeeThruHead** [comment] 2016-02-22 21:02
Yeah sorry here's a better screen
https://www.dropbox.com/s/31wsj8181eaj50b/Screenshot%202016-02-22%2016.01.03.png?dl=0

top one has height set on the div that is passed to devcard()

bottom one is default

the component has a popover element which is cut off by the end of the card.
I think that it wasn't doing this before, and an update caused it.

Thanks again.

**Comment by glenjamin** [comment] 2016-02-22 21:04
Should be fixed in febba74

**Closed by glenjamin** 2016-02-22 21:04 UTC
